name:                cfg-dsl
version:             0.1.0.0
github:              "githubuser/cfg-dsl"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cfg-dsl#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams
- diagrams-lib
- diagrams-contrib
- diagrams-svg
- diagrams-core
- mtl >= 2.2.2
- containers >= 0.5

library:
  source-dirs: src
  build-depends: 
    containers

executables:
  cfg-dsl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cfg-dsl

tests:
  cfg-dsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cfg-dsl
